DROP DATABASE IF EXISTS loodb;

CREATE DATABASE IF NOT EXISTS loodb;

USE loodb;

CREATE TABLE users (
    UNIQUE(email VARCHAR(20) NOT NULL),
    UNIQUE(usern VARCHAR(20) NOT NULL),
    passw VARCHAR(20) NOT NULL,
    
    user_id INT AUTO_INCREMENT PRIMARY KEY NOT NULL
);

CREATE TABLE buildings (
    bname VARCHAR(20) NOT NULL,
    baddress VARCHAR(255) NOT NULL,

    building_id INT AUTO_INCREMENT PRIMARY KEY NOT NULL
)
